VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 3
  end
  config.vm.box = "centos/8"
  config.disksize.size = "40GB"
  config.vm.network "private_network", ip: "192.168.44.44"
  
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'JoannaB'
  end
  
  config.vm.provision "shell", privileged: true, inline: <<-EOF
    adduser --disabled-password --gecos "" JoannaB
    usermod -aG sudo JoannaB
    mkdir -p /home/JoannaB/.ssh/
    cp /home/vagrant/.ssh/authorized_keys /home/JoannaB/.ssh/authorized_keys
    chown -R JoannaB:JoannaB /home/JoannaB
  EOF
end
