VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 3
  
  config.vm.box = "centos/8"
  config.disksize.size = "40GB"
  config.vm.network "private_network", ip: "192.168.44.44"
  end
end
