VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 3
  end
  config.vm.box = "centos/8"
  config.disksize.size = "40GB"
  config.vm.network "private_network", ip: "192.168.44.44"
  
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'joanna'
  end
  
  config.vm.provision "shell", privileged: true, inline: <<-EOF
    adduser --disabled-password --gecos "" joanna
    usermod -aG wheel joanna
    mkdir -p /home/joanna/.ssh/
    cp  /home/joanna/.ssh
    chown -R joanna:joanna /home/joanna
  EOF
end
